services:
  analytics:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M
  studio:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 384M
  kong:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 384M
  db:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 768M
  supavisor:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 256M
  realtime:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 256M
  meta:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 256M
  storage:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 256M
  functions:
    networks: [olivegarden]
    deploy:
      resources:
        limits:
          memory: 256M
  auth:
    networks: [olivegarden]
  rest:
    networks: [olivegarden]
  imgproxy:
    networks: [olivegarden]
  vector:
    networks: [olivegarden]

networks:
  olivegarden:
    external: true
